### ISSUE TITLE
which void-elements to choose

### ISSUE THREAD

**Issue by jeromew** [pugjs/void-elements#13]
@RobLoach I saw & merged your PRs (thanks).

I wanted to check if the project still works after the upgrade of `request` and realized that the list of void-elements has changed.

we currently have

    area,base,br,col,embed,hr,img,input,keygen,link,menuitem,meta,param,source,track,wbr

The list on https://w3c.github.io/html/syntax.html#void-element , which is used in pre-publish has

    area,base,br,col,embed,hr,img,input,link,menuitem,meta,param,source,track,wbr

so `keygen` is missing. This seems to be "HTML 5.2 Editor’s Draft, 11 December 2016"

I could find this commit - https://github.com/w3c/html/commit/f32520c686fe973116c208ff0a0dfc743d4d38cc that removes references to `keygen`

The HTML 5.1 list could be extracted without modification from https://www.w3.org/TR/html51/syntax.html

but the project README states that "The list is programatically generated from the latest W3C HTML draft.".

now what are we supposed to do with this in the spirit of the `void-elements` module and @ForbesLindesay what does pugjs wants to do with this ? target the latest draft ? the latest spec ? handle version of the modules mapped to the the version of the spec ? fetch the different versions and export them for a dynamic choice of void-elements ?

At this stage, I did not publish a new module.

**Comment by RobLoach** [comment]
Says **latest**, so it is working. No more `<keygen>`.

**Comment by jeromew** [comment]
ok so let's keep the **latest** approach and see if someone complains. I'll publish a new major version
